ALTER SESSION SET CONTAINER = XEPDB1;
ALTER SESSION SET CURRENT_SCHEMA = recipeasy;

alter table recipe_steps add constraint FKrecipe_ste331844 foreign key (recipe_id) references recipes (id);
alter table ingredient_recipe add constraint FKingredient186633 foreign key (ingredient_id) references ingredients (id);
alter table ingredient_recipe add constraint FKingredient598584 foreign key (recipe_id) references recipes (id);
alter table tag_recipe add constraint FKtag_recipe445422 foreign key (tag_id) references tags (id);
alter table tag_recipe add constraint FKtag_recipe353025 foreign key (recipe_id) references recipes (id);
alter table recipe_category_recipe add constraint FKrecipe_cat965049 foreign key (category_id) references recipe_categories (id);
alter table recipe_category_recipe add constraint FKrecipe_cat121919 foreign key (recipe_id) references recipes (id);
alter table chefs add constraint FKchefs76314 foreign key (user_id) references users (id);
alter table recipes add constraint FKrecipes440608 foreign key (chef_id) references chefs (id);
alter table ingredient_recipe add constraint FKingredient678132 foreign key (units_id) references units (id);
alter table recipe_access add constraint FKrecipe_acc848939 foreign key (user_id) references users (id);
alter table recipe_access add constraint FKrecipe_acc194063 foreign key (recipe_id) references recipes (id);
alter table ratings add constraint FKratings47708 foreign key (user_id) references users (id);
alter table favorites add constraint FKfavorites791699 foreign key (user_id) references users (id);
alter table favorites add constraint FKfavorites136888 foreign key (recipe_id) references recipes (id);
alter table ratings add constraint FKratings995294 foreign key (recipe_id) references recipes (id);
alter table notifications add constraint FKnotificati804334 foreign key (user_id) references users (id);
alter table recipe_list add constraint FKrecipe_lis322764 foreign key (user_id) references users (id);
alter table recipe_list_recipe add constraint FKrecipe_lis92413 foreign key (recipe_list_id) references recipe_list (id);
alter table recipe_list_recipe add constraint FKrecipe_lis531965 foreign key (recipe_id) references recipes (id);
alter table ingredient_allergen add constraint FKingredient721557 foreign key (ingredient_id) references ingredients (id);
alter table ingredient_allergen add constraint FKingredient720211 foreign key (allergen_id) references allergens (id);
alter table media add constraint FKmedia347653 foreign key (recipe_step_id) references recipe_steps (id);
alter table users add constraint FKusers162913 foreign key (role_id) references roles (id);
alter table cuisine_recipes add constraint FKcuisine_re426437 foreign key (cuisineid) references cuisine (id);
alter table cuisine_recipes add constraint FKcuisine_re836490 foreign key (recipesid) references recipes (id);
alter table comments add constraint FKcomments961395 foreign key (recipe_id) references recipes (id);
alter table comments add constraint FKcomments967191 foreign key (user_id) references users (id);
alter table ingredient_categories_ingredients add constraint FKingredient586548 foreign key (ingredient_categoriesid) references ingredient_categories (id);
alter table ingredient_categories_ingredients add constraint FKingredient159970 foreign key (ingredientsid) references ingredients (id);